apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver
  labels:
    app: kube-apiserver
spec:
  type: NodePort
  ports:
  - port: 6443 
    targetPort: 6443
    nodePort: 30008
    protocol: TCP
  selector:
    component: kube-apiserver